"""add_more_optional_columns_to_user

Revision ID: 1351a8db650c
Revises: 6efddc2153ea
Create Date: 2026-02-19 13:55:13.280954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1351a8db650c'
down_revision: Union[str, Sequence[str], None] = '6efddc2153ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('street_adress', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('province', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'province')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street_adress')
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###
