"""add to emial to table users

Revision ID: 22e6c2e64f36
Revises: f3339817ded5
Create Date: 2026-02-12 18:06:30.235271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e6c2e64f36'
down_revision: Union[str, Sequence[str], None] = 'f3339817ded5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reading_states', 'users', ['current_page'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=254), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'reading_states', type_='foreignkey')
    # ### end Alembic commands ###
