"""delete campos start_hour, end_hour and created new  hour column

Revision ID: 3bb4a76d3971
Revises: 7017c444da1d
Create Date: 2026-02-26 10:04:41.159373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bb4a76d3971'
down_revision: Union[str, Sequence[str], None] = '7017c444da1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_bookings', sa.Column('hour', sa.Integer(), nullable=False))
    op.alter_column('room_bookings', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('room_bookings', 'room_id',
               existing_type=mysql.INTEGER(display_width=11),
              nullable=False)
    op.create_unique_constraint('uq_hour_room_date_booking', 'room_bookings', ['hour', 'room_id', 'date'])
    op.drop_constraint(
        constraint_name='check_start_hour_<_end_hour', 
        table_name='room_bookings', 
        type_='check'
    )
    op.drop_column('room_bookings', 'end_hour')
    op.drop_column('room_bookings', 'start_hour')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_bookings', sa.Column('start_hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('room_bookings', sa.Column('end_hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint('uq_hour_room_date_booking', 'room_bookings', type_='unique')
    op.alter_column('room_bookings', 'room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('room_bookings', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('room_bookings', 'hour')
    # ### end Alembic commands ###
