"""user id as foregin key

Revision ID: 6efddc2153ea
Revises: 22e6c2e64f36
Create Date: 2026-02-17 14:56:07.325423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efddc2153ea'
down_revision: Union[str, Sequence[str], None] = '22e6c2e64f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reading_states_ibfk_2'), 'reading_states', type_='foreignkey')
    op.create_foreign_key(None, 'reading_states', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reading_states', type_='foreignkey')
    op.create_foreign_key(op.f('reading_states_ibfk_2'), 'reading_states', 'users', ['current_page'], ['id'])
    # ### end Alembic commands ###
