"""changed_end_&_strat_date_to_hours_integers

Revision ID: 7017c444da1d
Revises: b0dc967e2d44
Create Date: 2026-02-24 11:22:41.677344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7017c444da1d'
down_revision: Union[str, Sequence[str], None] = 'b0dc967e2d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
