"""changed_end_&_strat_date_to_hours_integers

Revision ID: b0dc967e2d44
Revises: 96143e9df75e
Create Date: 2026-02-24 11:08:26.616787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0dc967e2d44'
down_revision: Union[str, Sequence[str], None] = '96143e9df75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_bookings', sa.Column('start_hour', sa.Integer(), nullable=True))
    op.add_column('room_bookings', sa.Column('end_hour', sa.Integer(), nullable=True))
    op.add_column('room_bookings', sa.Column('date', sa.Date(), nullable=True))
    op.drop_constraint(
        constraint_name='check_user_role', 
        table_name='room_bookings', 
        type_='check'
    )
    op.create_check_constraint(
        'check_start_hour_<_end_hour', 
        'room_bookings',           #
        'start_hour < end_hour'        
    )
    op.drop_column('room_bookings', 'start_datetime')
    op.drop_column('room_bookings', 'end_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_bookings', sa.Column('end_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('room_bookings', sa.Column('start_datetime', mysql.DATETIME(), nullable=True))
    op.drop_column('room_bookings', 'date')
    op.drop_column('room_bookings', 'end_hour')
    op.drop_column('room_bookings', 'start_hour')
    op.drop_constraint(
        'check_start_hour_<_end_hour', 
        'room_bookings', 
        type_='check'
    )
    # ### end Alembic commands ###
