"""Create user table, and establish relationships with reading_states

Revision ID: f3339817ded5
Revises: add_title_to_books
Create Date: 2026-02-12 16:39:56.864782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3339817ded5'
down_revision: Union[str, Sequence[str], None] = 'add_title_to_books'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), server_default='user', nullable=False),
    sa.CheckConstraint("rol IN ('user', 'admin')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('reading_states', 'user_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_states', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('users')
    # ### end Alembic commands ###
