services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: biblioteca
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - test_db_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  test_db_data:
