services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./data/certs/:/var/traefik/certs:rw

  db:
    image: mariadb:11
    container_name: mariadb-biblioteca
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: redis-biblioteca
    labels:
      - "traefik.enable=false"
    ports:
      - "6379:6379"

  authservice:
    container_name: authservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authservice.rule=Host(`authservice.ezaka.es`)"
      - "traefik.http.routers.authservice.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authservice.entrypoints=websecure"
      - "traefik.http.services.authservice.loadbalancer.server.port=8001"
      - "traefik.http.routers.authservice.tls=true"

    build:
      dockerfile: authorization/Dockerfile
      context: .
    ports:
      - 8001:8001
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./authorization/
          target: /app
          ignore:
            - .venv/

  api:
    container_name: api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.ezaka.es`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.entrypoints=websecure"
    build:
      dockerfile: fast-graphql/Dockerfile
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./fast-graphql
          target: /app
          ignore:
            - .venv/

  frontend:
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.ezaka.es`)"

      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

      - "traefik.http.routers.frontend.entrypoints=websecure"

      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

      # Rate limit Middleware
      - "traefik.http.routers.frontend.middlewares=test-ratelimit,test-errorpages"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=1"

      # Custom error pages Middleware
      - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
      - "traefik.http.middlewares.test-errorpages.errors.service=error"
      - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"

    build:
      dockerfile: svelte-graphql/Dockerfile
      context: .
    # expose:
    #   - "3000"
    # the specified port should be removed when using docker-compose --scale
    ports:
      - "3000:3000"
    env_file: svelte-graphql/.env
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./svelte-graphql
          target: /app/svelte-graphql/

  error:
    image: tarampampam/error-pages:3.8
    environment:
      - TEMPLATE_NAME=lost-in-space
    ports:
      - "8081:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error.rule=Host(`error.ezaka.es`)"
      - "traefik.http.routers.error.service=error"
      - "traefik.http.services.error.loadbalancer.server.port=8080"
      - "traefik.http.routers.error.entrypoints=web"

volumes:
  db_data:
    external: true
