#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)
root_project="$HOME/library/"

for FILE in $STAGED_FILES;
do

  FILE="${root_project}${FILE}"

  echo "Reviewing: $FILE"

  SIZE=$(stat -c%s $FILE)
  echo $SIZE

  # 5MB
  if [ $SIZE -gt 5242880 ]; then
    echo "ERROR: file $FILE exceeded the limit ($SIZE bytes)"
    echo "MAX SIZE IS 5MB"
    exit 1
  fi
done
