on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

          release-type: simple

      - name: Install uv
        if: ${{ steps.release.outputs.release_created }}
        uses: astral-sh/setup-uv@v7

      - name: Install pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v4

      - name: Upload release artifacts
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-artifact@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
